import type { RulePack } from '@ghostkey/core/types';

export const linkedin: RulePack = {
  id: 'linkedin',
  name: 'LinkedIn',
  hostPatterns: ['*.linkedin.com', 'linkedin.com'],
  priority: 10,
  selectors: [
    { selector: '.authentication-outlet', weight: 8, description: 'Main auth wall' },
    { selector: '[data-test-modal-id="join-now-modal"]', weight: 9 },
    { selector: '.artdeco-modal-overlay', weight: 7 },
    { selector: '.artdeco-modal', weight: 6 },
    { selector: '.contextual-sign-in-modal', weight: 9 },
    { selector: '.sign-in-modal', weight: 9 },
    { selector: '[class*="join-form"]', weight: 7 },
    { selector: '[class*="login-form"]', weight: 7 },
    { selector: '.scaffold-layout-toolbar__content [data-control-name="nav.join"]', weight: 3 },
    // Side-panel auth forms
    { selector: '[class*="contextual-sign-in"]', weight: 9, description: 'Side panel sign-in' },
    { selector: '[class*="sign-in-form-container"]', weight: 9 },
    { selector: '[class*="authentication"]', weight: 7 },
    { selector: '[class*="reg-form"]', weight: 8 },
    { selector: '[class*="join-form"]', weight: 8 },
    { selector: '[class*="login__form"]', weight: 8 },
    { selector: '[class*="sign-in-card"]', weight: 9 },
    { selector: '.sidebar-sign-in', weight: 9 },
    { selector: '[data-tracking-control-name*="auth"]', weight: 7 },
    { selector: '[class*="right-rail"] [class*="sign-in"]', weight: 9, description: 'Right rail sign-in' },
    { selector: '[class*="right-rail"] [class*="join"]', weight: 9 },
    { selector: '[class*="upsell"]', weight: 7, description: 'Upsell prompts' },
    // Google One Tap / auth forms from DOM inspection
    { selector: 'form.google-auth', weight: 9, description: 'Google One Tap auth form' },
    { selector: '.google-one-tap__module', weight: 9 },
    { selector: '#google-one-tap__container', weight: 9 },
    { selector: 'form[action*="login-submit"]', weight: 9 },
    { selector: '[class*="google-auth"]', weight: 8 },
    { selector: '.linkedin-tc__text', weight: 5, description: 'LinkedIn T&C in auth' },
    // Fixed bottom-right sign-in card (guest search pages)
    { selector: '.cta-modal', weight: 9, description: 'Fixed sign-in card' },
    { selector: '[data-id="sign-in-card"]', weight: 9 },
    { selector: '[data-id="sign-in-form"]', weight: 9 },
    { selector: '.sign-in-card', weight: 9 },
    { selector: '.sign-in-form__submit-btn--full-width', weight: 7 },
    { selector: '.see-all-results-cta', weight: 6, description: 'Join now CTA at bottom' },
    // Profile page contextual sign-in modal
    { selector: '.contextual-sign-in-modal__layout--stacked', weight: 9, description: 'Profile page sign-in modal' },
    { selector: '.contextual-sign-in-modal__sign-in-form', weight: 9 },
    { selector: '.contextual-sign-in-modal__join-now', weight: 8 },
    { selector: '.contextual-sign-in-modal__google-sign-in-primary', weight: 9 },
    { selector: '.contextual-sign-in-modal__sign-in-with-email-cta', weight: 8 },
  ],
  safeSelectors: [
    '.msg-overlay-conversation-bubble',
    'nav',
  ],
  scrollLockSelectors: ['body.overflow-hidden'],
  backdropSelectors: ['.artdeco-modal-overlay'],
};
